# Generated by Django 5.2 on 2025-05-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0003_idea_doer'),
        ('users', '0002_doer_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaComments', to='users.doer')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaComments', to='ideas.idea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.doer')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaLikes', to='ideas.idea')),
            ],
        ),
    ]
