# Generated by Django 5.2.4 on 2025-08-04 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_idea_reference_video_and_more'),
        ('reactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idealike',
            unique_together={('idea', 'author')},
        ),
    ]
