# Generated by Django 5.2 on 2025-05-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_doer'),
        ('reactions', '0001_initial'),
        ('users', '0002_doer_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaSubscriptions', to='users.doer')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaSubscriptions', to='ideas.idea')),
            ],
        ),
    ]
