# Generated by Django 5.2 on 2025-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_ideasubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacomment',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
