# Generated by Django 5.2.4 on 2025-08-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_alter_idealike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idealike',
            unique_together=set(),
        ),
    ]
