# Generated by Django 5.2 on 2025-05-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_ideacomment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reactions.ideacomment'),
        ),
    ]
