# Generated by Django 5.2 on 2025-05-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_rename_image_ideareferenceimage_reference_image_and_more'),
        ('reactions', '0004_ideacomment_parent'),
        ('users', '0005_alter_doer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idealike',
            unique_together={('idea', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='ideasubscription',
            unique_together={('idea', 'author')},
        ),
    ]
