# Generated by Django 5.2 on 2025-05-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_alter_idealike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idealike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ideasubscription',
            unique_together=set(),
        ),
    ]
