services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: doers_db
      POSTGRES_USER: kiripupsik
      POSTGRES_PASSWORD: kiriLLpup565567
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
