# Generated by Django 5.2 on 2025-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doer',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
