# Generated by Django 5.2 on 2025-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doer',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
