# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doer',
            name='nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
