# Generated by Django 5.2 on 2025-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doer_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doer',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
