# Generated by Django 5.2.4 on 2025-08-03 09:27

import django.db.models.deletion
import ideas.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='ideas/logos')),
                ('reference_video', models.FileField(blank=True, upload_to='ideas/videos', validators=[ideas.validators.validate_video_file])),
                ('category', models.CharField(choices=[('business_and_startups', 'Business and Startups'), ('technology_and_innovations', 'Technology and Innovations'), ('education_and_self_development', 'Education and Self-development'), ('ecology_and_sustainability', 'Ecology and Sustainability'), ('culture_and_arts', 'Culture and Arts'), ('health_and_well_being', 'Health and Well-being'), ('social_and_cultural_change', 'Social and Cultural Change'), ('transportation_and_logistics', 'Transportation and Logistics'), ('science_and_research', 'Science and Research'), ('travel_and_tourism', 'Travel and Tourism'), ('finance_and_investment', 'Finance and Investment'), ('internet_and_communications', 'Internet and Communications'), ('agriculture_and_animal_husbandry', 'Agriculture and Animal Husbandry'), ('psychology_and_relationships', 'Psychology and Relationships'), ('law_and_legal_affairs', 'Law and Legal Affairs'), ('gadgets_and_devices', 'Gadgets and Devices'), ('leisure_and_entertainment', 'Leisure and Entertainment'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.ImageField(upload_to='ideas/images')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea')),
            ],
        ),
    ]
