# Generated by Django 5.2.4 on 2025-08-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='reference_video',
        ),
        migrations.DeleteModel(
            name='IdeaReferenceImage',
        ),
    ]
