# Generated by Django 5.2 on 2025-04-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='test',
            new_name='image',
        ),
    ]
