# Generated by Django 5.2 on 2025-05-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_test_idea_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='doer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to='users.doer'),
            preserve_default=False,
        ),
    ]
