# Generated by Django 5.2 on 2025-05-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
