# Generated by Django 5.2 on 2025-05-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_idea_id'),
        ('users', '0003_alter_doer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='users.doer'),
        ),
    ]
