# Generated by Django 5.2 on 2025-05-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_idea_doer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='image',
        ),
        migrations.AddField(
            model_name='idea',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idea',
            name='reference_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
