# Generated by Django 5.2 on 2025-05-07 09:30

import django.db.models.deletion
import ideas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_remove_idea_image_idea_logo_idea_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('business_and_startups', 'Business and Startups'), ('technology_and_innovations', 'Technology and Innovations'), ('education_and_self_development', 'Education and Self-development'), ('ecology_and_sustainability', 'Ecology and Sustainability'), ('culture_and_arts', 'Culture and Arts'), ('health_and_well_being', 'Health and Well-being'), ('social_and_cultural_change', 'Social and Cultural Change'), ('transportation_and_logistics', 'Transportation and Logistics'), ('science_and_research', 'Science and Research'), ('travel_and_tourism', 'Travel and Tourism'), ('finance_and_investment', 'Finance and Investment'), ('internet_and_communications', 'Internet and Communications'), ('agriculture_and_animal_husbandry', 'Agriculture and Animal Husbandry'), ('psychology_and_relationships', 'Psychology and Relationships'), ('law_and_legal_affairs', 'Law and Legal Affairs'), ('gadgets_and_devices', 'Gadgets and Devices'), ('leisure_and_entertainment', 'Leisure and Entertainment'), ('other', 'Other')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='reference_video',
            field=models.FileField(default=0, upload_to='ideas/videos', validators=[ideas.validators.validate_video_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='slogan',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='logo',
            field=models.ImageField(blank=True, upload_to='ideas/logos'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='reference_image',
            field=models.ImageField(blank=True, upload_to='ideas/images'),
        ),
        migrations.CreateModel(
            name='IdeaReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ideas/images')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ideas.idea')),
            ],
        ),
    ]
