# Generated by Django 5.2 on 2025-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_remove_idea_image_idea_logo_idea_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
