# Generated by Django 5.2 on 2025-05-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_idea_category_idea_reference_video_idea_slogan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideareferenceimage',
            old_name='image',
            new_name='reference_image',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='reference_image',
        ),
    ]
