# Generated by Django 5.2 on 2025-05-13 06:01

import ideas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_rename_image_ideareferenceimage_reference_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='reference_video',
            field=models.FileField(blank=True, upload_to='ideas/videos', validators=[ideas.validators.validate_video_file]),
        ),
    ]
